version: '3'
services: 
    app:
        build: .
        ports: 
            - ${HTTP_PORT}:80
            - ${HTTPS_PORT}:443
        environment: 
            - ConnectionStrings:DefaultConnection= ${CONNECTION_STRING}

